# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180529_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='jre2017.png', upload_to='post/'),
        ),
    ]
