# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_categorie_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default=1, help_text='Consultez la liste des logo possible <a href="../../../../../documentation#color">ici', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='color',
            field=models.CharField(help_text='Consultez la liste des couleur possible <a href="../../../../../documentation#color">ici', max_length=30),
        ),
    ]
